//
// INTEL CONFIDENTIAL
// Copyright 2017 Intel Corporation.
//
// This software and the related documents are Intel copyrighted materials, and your use of them is governed
// by the express license under which they were provided to you (License). Unless the License provides otherwise,
// you may not use, modify, copy, publish, distribute, disclose or transmit this software or the related documents
// without Intel's prior written permission.
//
// This software and the related documents are provided as is, with no express or implied warranties, other than
// those that are expressly stated in the License.
//

package broker

import (
	mqtt "github.com/eclipse/paho.mqtt.golang"
)

// JSONSchema is a generic JSON schema representation.
// Values of the map can either be strings or nested instances of JSONSchema
type JSONSchema map[string]interface{}

// ProviderItemChannel is a type definition for a channel to return JSONSchema pointers
type ProviderItemChannel chan *ItemData
type ItemChannel chan *JSONSchema

// ErrorData is a type definition of objects of type error
type ErrorData struct {
	Error error
}

// ErrorChannel is a type definition for a channel to report errors that occur in core
type ErrorChannel chan ErrorData

// BrokerStarted is a type definition of a bool value, to indicate if sensing has started or not
type BrokerStarted struct {
	Started bool
}

// BrokerStartedChannel is a type definition for a channel to return that sensing has started or not
type BrokerStartedChannel chan *BrokerStarted

type MosquittoProvider struct {
	onItem  ProviderItemChannel
	onError ErrorChannel
	options *MosquittoProviderOptions
}

type MosquittoProviderOptions struct {
	MttqClient               mqtt.Client
	Gateway                  string
	Username                 string
	Password                 string
	Topics                   []string
	AllowSelfSignedCerts     bool
	EncryptGatewayConnection bool
	OnStarted                BrokerStartedChannel
	OnError                  ErrorChannel
}

// ItemData is a generic representation of all objects generated by providers in the
// Context Sensing Go SDK
type ItemData struct {
	MacAddress  string      `json:"macaddress"`
	Application string      `json:"application"`
	ProviderID  int         `json:"providerId"`
	DateTime    string      `json:"dateTime"`
	Type        string      `json:"type"`
	Value       interface{} `json:"value"`
}
